rules/detect-no-csrf-before-method-override.js

Fixed crash with `detect-no-csrf-before-method-override` rule.
It's possible to do
```js
const app = express();
```

Fixed crash with `detect-no-csrf-before-method-override` rule

---

.eslintrc
README.md
package.json
rules/detect-buffer-noassert.js
rules/detect-child-process.js
rules/detect-non-literal-fs-filename.js
rules/detect-non-literal-regexp.js
rules/detect-non-literal-require.js
rules/detect-pseudoRandomBytes.js
test/detect-buffer-noassert.js
test/detect-child-process.js
test/detect-disable-mustache-escape.js
test/detect-eval-with-expression.js
test/detect-new-buffer.js
test/detect-no-csrf-before-method-override.js
test/detect-non-literal-fs-filename.js
test/detect-non-literal-regexp.js
test/detect-non-literal-require.js
test/detect-object-injection.js
test/detect-possible-timing-attacks.js
test/detect-pseudoRandomBytes.js
test/detect-unsafe-regexp.js

Tests implemented, a fix and minor typos. :)

A bit of love

---

README.md

Fixes #1. I appreciated the individual response to that issue, but everyone needs that information.
Lemme know what you think about the links I've chosen!

Add additional information to README for each rule

---

README.md

The current link leads to a 404 page, the new one is the proper page.

Fix broken link for detect-object-injection

---

rules/detect-buffer-noassert.js
rules/detect-child-process.js
rules/detect-new-buffer.js
rules/detect-non-literal-fs-filename.js
rules/detect-non-literal-regexp.js
rules/detect-non-literal-require.js
rules/detect-object-injection.js
rules/detect-possible-timing-attacks.js
rules/detect-pseudoRandomBytes.js
test/detect-buffer-noassert.js
test/detect-child-process.js
test/detect-new-buffer.js
test/detect-non-literal-fs-filename.js
test/detect-non-literal-regexp.js
test/detect-non-literal-require.js
test/detect-object-injection.js
test/detect-possible-timing-attacks.js
test/detect-pseudoRandomBytes.js

Remove filename from error output

---

CHANGELOG.md
package.json

Add basic CHANGELOG.md file

---

README.md

Changed the dead link for `detect-child-process` as the original link is dead
https://web.archive.org/web/20140903015907/https://blog.liftsecurity.io/2014/08/19/Avoid-Command-Injection-Node.js

Use archived link for child_process as original is dead.

---

README.md

The detect-unsafe-regex link was dead, replaced with a link to an archived version
https://web.archive.org/web/20170131192028/https://blog.liftsecurity.io/2014/11/03/regular-expression-dos-and-node.js

Replace dead link with archived link for Regex Vulns.

---

README.md

The link for 
https://blog.liftsecurity.io/2015/01/14/the-dangers-of-square-bracket-notation/
Is offline
For now point to an archived version so people can still have access to this information.
https://web.archive.org/web/20150430062816/https://blog.liftsecurity.io/2015/01/15/the-dangers-of-square-bracket-notation

Update the square bracket link as the original is down.

---

package.json

v2.0.0 tweaks safe-regex's heuristic to address some false negatives.

Bump safe-regex version

---

README.md

The `plugins` array is only needed if one is not using the config (or a config which doesn't add to `plugins`).

No need for `plugins` since the `recommended` config already includes it

---

README.md

In the blog article https://snyk.io/blog/node-js-timing-attack-ccc-ctf/ they are talking about timing attack in a context of password security. Then providing a vulnerable and not vulnerable code examples:
vulnerable:
```
function isAuthenticated(user, token) {
var correctToken = FetchUserTokenFromDB(user);
return token === correctToken;
}
```
not vulnerable:
```
var mismatch = 0;
for (var i = 0; i < a.length; ++i) {
mismatch |= (a.charCodeAt(i) ^ b.charCodeAt(i));
}
return mismatch;
```
But the 2nd code makes a wrong check. E.g. it will return 0 (zero mismatches) when a: "123" and b: "123asd". So it should not be used to compare tokens/passwords/etc. At least as is. It should include length check, like in the example from codahale: …

Better link to time attack explanation

---

package-lock.json
package.json
rules/detect-non-literal-require.js
test/detect-non-literal-require.js

I did not have write access to the fork for #32, so i forked the fork and implemented the following changes:
- This PR has resolved the merge conflicts currently on #32.
- The old PR failed 16 tests due to ESLint >6 requiring absolute parser paths for rule testers. This is resolved. More info:
https://github.com/eslint/eslint/blob/main/docs/user-guide/migrating-to-6.0.0.md#rule-tester-parser
This closes #29  and #27 
@nzakas Can you close #32 in favor of this pr, and possibly merge?

feat(non-literal-require): support template literals

---

.eslintrc
package-lock.json
package.json
rules/detect-buffer-noassert.js
rules/detect-child-process.js
rules/detect-disable-mustache-escape.js
rules/detect-eval-with-expression.js
rules/detect-new-buffer.js
rules/detect-no-csrf-before-method-override.js
rules/detect-non-literal-fs-filename.js
rules/detect-non-literal-regexp.js
rules/detect-non-literal-require.js
rules/detect-object-injection.js
rules/detect-possible-timing-attacks.js
rules/detect-pseudoRandomBytes.js
rules/detect-unsafe-regex.js

Includes:
* Adds [eslint-plugin-eslint-plugin](https://www.npmjs.com/package/eslint-plugin-eslint-plugin) which is recommended for all [ESLint plugins](https://eslint.org/docs/latest/developer-guide/working-with-plugins)
* Enables the `recommended` rules from this plugin except for a few with more violations which can be enabled later
* Autofixed all violations
* Inconsistent / missing rule doc URLs
* Old-style arguments for `context.report()`

chore: add `eslint-plugin-eslint-plugin`

---

.github/workflows/ci.yml
.github/workflows/pr.yml

This PR:
-   Removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false, they are not used after the initial checkout
-   Declares the minimum permissions for CI workflows to run at the job level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
-   Bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)

ci: update workflows

---

rules/detect-child-process.js
test/detect-child-process.js

This extends the fix in 7f97815accf6bcd87de73c32a967946b1b3b0530
In some situations, such as code using a sinon stub, a TypeError is thrown as the AST node has no 'arguments' property.
Closes 69
Refs 69

fix: Avoid TypeError when exec stub is used with no arguments

---

rules/detect-child-process.js
test/detect-child-process.js

This PR fixes false positives in detect-child-process.
`detect-child-process` rule did not understand destructuring assignment and was incorrectly reporting non-identifier `exec()`.
This PR changes the `detect-child-process` rule to guard non-identifiers and correctly track variables.
fixes #64

fix(detect-child-process): false positive for destructuring with `exec`

---

rules/detect-child-process.js
test/detect-child-process.js

This PR fixes false positives in detect-child-process.
With this change, calls to `require("child_process")` will no longer be reported if destructuring assignment is used.
fixes #51

fix(detect-child-process): false positives for destructuring `spawn`

---

rules/detect-child-process.js
test/detect-child-process.js

close #104
This PR improves the `detect-child-process` rule with the following changes:
- Changed to check module imports as well.
- Changed to check import of `node:child_process`.
- Changed to report immediate calls like `require('child_process').exec(c)`.
- Changed to report `exec(c)` calls with destructuring.
- Changed to not report traceable `require('child_process')`.

feat: improve detect-child-process rule

---

docs/the-dangers-of-square-bracket-notation.md

Discovered this square bracket notation page via an [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared) -- was deeply confused by the significance of the hyperlink to requiresafe.com until I looked at archive.org and understood that it's been repurposed by a different brand.  Offered a suggestion for a paraphrase that isn't dependent on the context of the original link, but the point is likely sufficiently clear without the sentence being there at all.
(Also, haven't submitted a change request/PR directly from GH markdown edit before; apologies if I'm not doing this quite right.)

docs(the-dangers-of-square-bracket-notation): fix broken link

---

README.md
index.js

This PR adds support for the [new eslint config](https://eslint.org/docs/latest/use/configure/configuration-files-new), an example:
```js
// eslint.config.js
const pluginSecurity = require('eslint-plugin-security');
module.exports = [pluginSecurity.configs.recommended];
```

feat!: switch the recommended config to flat

---

.eslint-doc-generatorrc.js
README.md
index.js
test/configs/index.js
test/rules/detect-bidi-characters.js
test/rules/detect-buffer-noassert.js
test/rules/detect-child-process.js
test/rules/detect-disable-mustache-escape.js
test/rules/detect-eval-with-expression.js
test/rules/detect-new-buffer.js
test/rules/detect-no-csrf-before-method-override.js
test/rules/detect-non-literal-fs-filename.js
test/rules/detect-non-literal-regexp.js
test/rules/detect-non-literal-require.js
test/rules/detect-object-injection.js
test/rules/detect-possible-timing-attacks.js
test/rules/detect-pseudoRandomBytes.js
test/rules/detect-unsafe-regexp.js

it also moves rule tests to `./test/rules/`, and adds a test for the configs.
fixes #131

feat: add config recommended-legacy

---

rules/detect-eval-with-expression.js
test/rules/detect-eval-with-expression.js

fixes #138
Setting as draft pending response to https://github.com/eslint-community/eslint-plugin-security/issues/138#issuecomment-1942205808

fix: Ensure empty eval() doesn't crash detect-eval-with-expression

---

docs/regular-expression-dos-and-node.md

docs: fix typos in regular expression docs

---

package-lock.json
package.json
rules/detect-bidi-characters.js
rules/detect-buffer-noassert.js
rules/detect-child-process.js
rules/detect-disable-mustache-escape.js
rules/detect-new-buffer.js
rules/detect-no-csrf-before-method-override.js
rules/detect-non-literal-fs-filename.js
rules/detect-non-literal-regexp.js
rules/detect-non-literal-require.js
rules/detect-object-injection.js
rules/detect-possible-timing-attacks.js
rules/detect-pseudoRandomBytes.js
rules/detect-unsafe-regex.js
test/rules/detect-child-process.js
test/rules/detect-non-literal-fs-filename.js
test/rules/detect-non-literal-require.js
test/utils/import-utils.js
test/utils/is-static-expression.js

Updated APIs and dependencies to work with ESLint v9.
fixes #144

fix: Ensure everything works with ESLint v9

---

.github/workflows/pr.yml

it fixes the ci check failing, e.g. https://github.com/eslint-community/eslint-plugin-security/actions/runs/9499881665/job/26181774866

ci: upgrade beemojs/conventional-pr-action v3

---

.github/workflows/release-please.yml

This will also add a new Provenance section + a verified badge next to the version (in the sidebar + versions tab) to the NPM page
More info can be found at https://docs.npmjs.com/generating-provenance-statements

chore: generate provenance statements on release

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.github/workflows/release-please.yml

This PR bumps GitHub Actions to their latest major versions. Main change is they are now using Node 20 instead of 16, which was EOL as of April 2022:
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
At the same time, testing on EOL Node 21 has been swapped out for Node 22, and the package is now built in `release-please.yml` using node 18 rather than EOL Node 16.

ci: update github actions
